require "user.impatient"
require "user.keymaps"
require "user.options"
require "user.plugins"
require "user.comment"
require "user.nvim-tree"
require "user.telescope"
require "user.colorscheme"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
require "user.whichkey"
require "user.alpha"
require "user.treesitter"
require "user.gitsigns"

-- require "user.cmp"
require "user.notify"
require "user.lsp"
-- require "user.autopairs"
-- require "user.project"
-- require "user.autocommands"

-- require "user.rust-tools"
